// <auto-generated />
namespace Uprise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class campaign_email_response : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campaign_email_response));
        
        string IMigrationMetadata.Id
        {
            get { return "201902241929504_campaign_email_response"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
